SELECT [Booking ID]
      ,[Booking Date]
      ,[Arrival Date]
      ,[Reservation Status Date]
      ,[Reservation Status]
      ,[Is Canceled]
      ,[Lead Time]
      ,[Nights Weekend]
      ,[Nights Weekday]
      ,[Adults]
      ,[Children]
      ,[Babies]
      ,[Meal]
      ,[Is Repeated Guest]
      ,[Bookings Canceled]
      ,[Bookings Not Canceled]
      ,[Reserved Room Type]
      ,[Assigned Room Type]
      ,[Booking Changes]
      ,[Company]
      ,[Avg Daily Rate]
      ,[Total Nights]
      ,[Market Segment Key]
      ,[Hotel Type Key]
      ,[Channel Key]
      ,[Deposit Type Key]
      ,[Customer Type Key]
      ,[Days In Waiting List]
  FROM [Bookings_DB].[dbo].[Bookings]
  where [Booking ID] >      --Use Variable Last_Load_BookingID_Bk
		[Booking Date] >=   --Use Variable Last_Load_Date
		[Booking Date] <    --Use Variable StartTime